In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/MyDrive/Biomarker_Project')

In [ ]:
!ls

bert_tokenizer		    FDA_therapy_biomarker_extraction.ipynb
biomarker_nlp		    Final_Biomarker_Report.csv
biomarker_nlp_1		    Final_Biomarker_Report.gsheet
biomarker_output.csv	    negCue
biomarker_output.gsheet     negScope
biomarker_report_final.csv  NLP_Biomarker_Extraction.ipynb
biomarkers.csv		    therapy_extraction.txt
checkpoint_1.csv	    therapy_links

In [ ]:
with open('therapy_extraction.txt','r') as file:
  therapies = file.read().split(',')

In [ ]:
len(therapies)

748

In [ ]:
!pip install scispacy

Collecting scispacy
  Downloading scispacy-0.6.2-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: spacy<3.9.0,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from scispacy) (3.8.14)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.16.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from scispacy) (2.32.4)
Collecting conllu (from scispacy)
  Downloading conllu-6.0.0-py3-none-any.whl.metadata (21 kB)
Collecting numpy<2.0 (from scispacy)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.1 MB/s eta 0:00:00
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.5.3)
Collecting nmslib-metabrainz==2.1.3 (from scispacy)
  Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (956 bytes)
Requirement already satisfied: scikit-learn>=0.20.3 in /usr/local/lib/python3.12/dist-packages (from scispacy) (1.6.1)
Collecting pysbd (from scispacy)
  Downloading pysbd-0.3.4-py3-none-any.whl.metadata (6.1 kB)
Collecting pybind11>=2.2.3 (from nmslib-metabrainz==2.1.3->scispacy)
  Downloading pybind11-3.0.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from nmslib-metabrainz==2.1.3->scispacy) (5.9.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->scispacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->scispacy) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->scispacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->scispacy) (2026.4.22)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.3->scispacy) (3.6.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (4.67.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.9.0,>=3.7.0->scispacy) (26.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy<3.9.0,>=3.7.0->scispacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy<3.9.0,>=3.7.0->scispacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.4.2)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy<3.9.0,>=3.7.0->scispacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<3.9.0,>=3.7.0->scispacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy<3.9.0,>=3.7.0->scispacy) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.9.0,>=3.7.0->scispacy) (0.1.2)
Downloading scispacy-0.6.2-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 5.5 MB/s eta 0:00:00
Downloading nmslib_metabrainz-2.1.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 109.1 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 103.1 MB/s eta 0:00:00
Downloading conllu-6.0.0-py3-none-any.whl (16 kB)
Downloading pysbd-0.3.4-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.1/71.1 kB 8.4 MB/s eta 0:00:00
Downloading pybind11-3.0.4-py3-none-any.whl (314 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.2/314.2 kB 36.7 MB/s eta 0:00:00
Installing collected packages: pysbd, pybind11, numpy, conllu, nmslib-metabrainz, scispacy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed conllu-6.0.0 nmslib-metabrainz-2.1.3 numpy-1.26.4 pybind11-3.0.4 pysbd-0.3.4 scispacy-0.6.2

In [ ]:
from biomarker_nlp import biomarker_extraction

In [ ]:
import pandas as pd
from tqdm import tqdm

skeleton_data = []
for full_url in tqdm(therapies, desc="Pass 1: Metadata"):
    try:
        name = biomarker_extraction.targeted_therapy_name(full_url)[0]
        diseases = biomarker_extraction.therapy_disease(full_url)
        dm_url = biomarker_extraction.drug_search_url(full_url)[0]

        brand = biomarker_extraction.drug_brand_label(dm_url)
        ndc = biomarker_extraction.ndc_code(dm_url)

        for dis in diseases:
            content = biomarker_extraction.disease_content(dm_url, dis)
            skeleton_data.append({
                "therapy_label": name,
                "disease_label": dis,
                "drug_label": brand,
                "raw_text": content
            })
    except: continue

df = pd.DataFrame(skeleton_data)
df.to_csv("biomarkers.csv", index=False)

Pass 1: Metadata: 100%|██████████| 748/748 [21:05<00:00,  1.69s/it]

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("biomarkers.csv")

In [ ]:
df.count()

therapy_label    1464
disease_label    1464
drug_label        892
raw_text          384
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.head(5)

,therapy_label,disease_label,drug_label,raw_text
0,Idecabtagene Vicleucel,multiple myeloma,ABECMA- idecabtagene vicleucel suspension,NaN
1,Abemaciclib,Breast cancer,VERZENIO- abemaciclib tablet,\nVERZENIO® (abemaciclib) is indicated:\n\n\n\...
2,Abiraterone Acetate,Prostate cancer,ZYTIGA- abiraterone acetate tablet,NaN
3,Paclitaxel Albumin-stabilized Nanoparticle For...,Pancreatic cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",NaN
4,Paclitaxel Albumin-stabilized Nanoparticle For...,Breast cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",\nABRAXANE is indicated for the treatment of b...

In [ ]:
df.count()

therapy_label    384
disease_label    384
drug_label       384
raw_text         384
dtype: int64

In [ ]:
|!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz

Collecting https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz
  Downloading https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz (119.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 12.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting spacy<3.8.0,>=3.7.4 (from en_ner_bionlp13cg_md==0.5.4)
  Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.0.13)
Collecting thinc<8.3.0,>=8.2.2 (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.0.10)
Collecting weasel<0.5.0,>=0.1.0 (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (4.67.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (26.1)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading langcodes-3.5.1-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.26.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2026.4.22)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.0.4)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (7.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.1.2)
Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 72.3 MB/s eta 0:00:00
Downloading langcodes-3.5.1-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 kB 18.4 MB/s eta 0:00:00
Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (865 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.0/865.0 kB 58.4 MB/s eta 0:00:00
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 kB 6.3 MB/s eta 0:00:00
Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 105.0 MB/s eta 0:00:00
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Building wheels for collected packages: en_ner_bionlp13cg_md
  Building wheel for en_ner_bionlp13cg_md (setup.py) ... done
  Created wheel for en_ner_bionlp13cg_md: filename=en_ner_bionlp13cg_md-0.5.4-py3-none-any.whl size=119814670 sha256=e1d29516671454ca52959fcde9aba40f6acbf8fa7ec1a2b5ae6fb302fe39b2fd
  Stored in directory: /root/.cache/pip/wheels/95/ca/35/7a25decd9a4965ccae588698b6d96f92e1c6816d805f509590
Successfully built en_ner_bionlp13cg_md
Installing collected packages: langcodes, blis, confection, thinc, weasel, spacy, en_ner_bionlp13cg_md
  Attempting uninstall: blis
    Found existing installation: blis 1.3.3
    Uninstalling blis-1.3.3:
      Successfully uninstalled blis-1.3.3
  Attempting uninstall: confection
    Found existing installation: confection 1.3.3
    Uninstalling confection-1.3.3:
      Successfully uninstalled confection-1.3.3
  Attempting uninstall: thinc
    Found existing installation: thinc 8.3.13
    Uninstalling thinc-8.3.13:
      Successfully uninstalled thinc-8.3.13
  Attempting uninstall: weasel
    Found existing installation: weasel 1.0.0
    Uninstalling weasel-1.0.0:
      Successfully uninstalled weasel-1.0.0
  Attempting uninstall: spacy
    Found existing installation: spacy 3.8.14
    Uninstalling spacy-3.8.14:
      Successfully uninstalled spacy-3.8.14
Successfully installed blis-0.7.11 confection-0.1.5 en_ner_bionlp13cg_md-0.5.4 langcodes-3.5.1 spacy-3.7.5 thinc-8.2.5 weasel-0.4.3

In [ ]:
import spacy
import torch
import gc

nlp = spacy.load("en_ner_bionlp13cg_md")

def extract_genes(text):
    if pd.isna(text) or not isinstance(text, str): return "*"
    doc = nlp(text)
    found = [ent.text for ent in doc.ents if ent.label_ in ["GENE_OR_GENE_PRODUCT", "PROTEIN"]]
    return ", ".join(list(set(found))) if found else "*"

df["geneProtein_label"] = df["raw_text"].apply(extract_genes)
del nlp
gc.collect()
torch.cuda.empty_cache()

In [ ]:
df

,therapy_label,disease_label,drug_label,raw_text,geneProtein_label
0,Idecabtagene Vicleucel,multiple myeloma,ABECMA- idecabtagene vicleucel suspension,NaN,*
1,Abemaciclib,Breast cancer,VERZENIO- abemaciclib tablet,\nVERZENIO® (abemaciclib) is indicated:\n\n\n\...,aromatase
2,Abiraterone Acetate,Prostate cancer,ZYTIGA- abiraterone acetate tablet,NaN,*
3,Paclitaxel Albumin-stabilized Nanoparticle For...,Pancreatic cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",NaN,*
4,Paclitaxel Albumin-stabilized Nanoparticle For...,Breast cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",\nABRAXANE is indicated for the treatment of b...,ABRAXANE
...,...,...,...,...,...
1459,Idelalisib,Chronic lymphocytic leukemia,"ZYDELIG- idelalisib tablet, film coated",NaN,*
1460,Ceritinib,Non-small cell lung cancer,"ZYKADIA- ceritinib tablet, film coated",NaN,*
1461,Loncastuximab Tesirine-lpyl,B-cell non-Hodgkin lymphoma,"ZYNLONTA- loncastuximab tesirine injection, po...",NaN,*
1462,Retifanlimab-dlwr,Merkel cell carcinoma,ZYNYZ- retifanlimab-dlwr injection,\n\nZYNYZ is indicated for the treatment of ad...,*
1463,Abiraterone Acetate,Prostate cancer,ZYTIGA- abiraterone acetate tablet,NaN,*

In [ ]:
nlp = spacy.load("en_ner_bionlp13cg_md")

In [ ]:
!pip install knockknock

Collecting knockknock
  Downloading knockknock-0.1.8.1-py3-none-any.whl.metadata (17 kB)
Collecting yagmail>=0.11.214 (from knockknock)
  Downloading yagmail-0.15.293-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: keyring in /usr/local/lib/python3.12/dist-packages (from knockknock) (25.7.0)
Collecting matrix-client (from knockknock)
  Downloading matrix_client-0.4.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting python-telegram-bot (from knockknock)
  Downloading python_telegram_bot-22.7-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from knockknock) (2.32.4)
Collecting twilio (from knockknock)
  Downloading twilio-9.10.5-py2.py3-none-any.whl.metadata (13 kB)
Collecting premailer (from yagmail>=0.11.214->knockknock)
  Downloading premailer-3.10.0-py2.py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: SecretStorage>=3.2 in /usr/local/lib/python3.12/dist-packages (from keyring->knockknock) (3.5.0)
Requirement already satisfied: jeepney>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from keyring->knockknock) (0.9.0)
Requirement already satisfied: jaraco.classes in /usr/local/lib/python3.12/dist-packages (from keyring->knockknock) (3.4.0)
Requirement already satisfied: jaraco.functools in /usr/local/lib/python3.12/dist-packages (from keyring->knockknock) (4.4.0)
Requirement already satisfied: jaraco.context in /usr/local/lib/python3.12/dist-packages (from keyring->knockknock) (6.1.2)
Collecting urllib3~=1.21 (from matrix-client->knockknock)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 4.2 MB/s eta 0:00:00
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->knockknock) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->knockknock) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->knockknock) (2026.4.22)
Requirement already satisfied: httpx<0.29,>=0.27 in /usr/local/lib/python3.12/dist-packages (from python-telegram-bot->knockknock) (0.28.1)
Requirement already satisfied: PyJWT<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from twilio->knockknock) (2.12.1)
Requirement already satisfied: aiohttp>=3.8.4 in /usr/local/lib/python3.12/dist-packages (from twilio->knockknock) (3.13.5)
Collecting aiohttp-retry>=2.8.3 (from twilio->knockknock)
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.8.4->twilio->knockknock) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.8.4->twilio->knockknock) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.8.4->twilio->knockknock) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.8.4->twilio->knockknock) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.8.4->twilio->knockknock) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.8.4->twilio->knockknock) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.8.4->twilio->knockknock) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.27->python-telegram-bot->knockknock) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.27->python-telegram-bot->knockknock) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29,>=0.27->python-telegram-bot->knockknock) (0.16.0)
Requirement already satisfied: cryptography>=2.0 in /usr/local/lib/python3.12/dist-packages (from SecretStorage>=3.2->keyring->knockknock) (43.0.3)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from jaraco.classes->keyring->knockknock) (10.8.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from premailer->yagmail>=0.11.214->knockknock) (6.1.0)
Collecting cssselect (from premailer->yagmail>=0.11.214->knockknock)
  Downloading cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Collecting cssutils (from premailer->yagmail>=0.11.214->knockknock)
  Downloading cssutils-2.15.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from premailer->yagmail>=0.11.214->knockknock) (6.2.6)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp>=3.8.4->twilio->knockknock) (4.15.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=2.0->SecretStorage>=3.2->keyring->knockknock) (2.0.0)
Collecting encutils (from cssutils->premailer->yagmail>=0.11.214->knockknock)
  Downloading encutils-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2->keyring->knockknock) (3.0)
Requirement already satisfied: chardet in /usr/local/lib/python3.12/dist-packages (from encutils->cssutils->premailer->yagmail>=0.11.214->knockknock) (5.2.0)
Downloading knockknock-0.1.8.1-py3-none-any.whl (28 kB)
Downloading yagmail-0.15.293-py2.py3-none-any.whl (17 kB)
Downloading matrix_client-0.4.0-py2.py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 5.2 MB/s eta 0:00:00
Downloading python_telegram_bot-22.7-py3-none-any.whl (745 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 745.4/745.4 kB 29.1 MB/s eta 0:00:00
Downloading twilio-9.10.5-py2.py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 84.9 MB/s eta 0:00:00
Downloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 17.6 MB/s eta 0:00:00
Downloading premailer-3.10.0-py2.py3-none-any.whl (19 kB)
Downloading cssselect-1.4.0-py3-none-any.whl (18 kB)
Downloading cssutils-2.15.0-py3-none-any.whl (180 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.6/180.6 kB 23.2 MB/s eta 0:00:00
Downloading encutils-1.0.0-py3-none-any.whl (21 kB)
Installing collected packages: urllib3, encutils, cssselect, cssutils, python-telegram-bot, premailer, matrix-client, aiohttp-retry, yagmail, twilio, knockknock
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
blobfile 3.2.0 requires urllib3>=2, but you have urllib3 1.26.20 which is incompatible.
Successfully installed aiohttp-retry-2.9.1 cssselect-1.4.0 cssutils-2.15.0 encutils-1.0.0 knockknock-0.1.8.1 matrix-client-0.4.0 premailer-3.10.0 python-telegram-bot-22.7 twilio-9.10.5 urllib3-1.26.20 yagmail-0.15.293

In [ ]:
import torch
import __main__
import inspect
import gc
import torch.nn.functional as F
import transformers.models.xlnet.modeling_xlnet as xlnet_mod
from transformers import XLNetForTokenClassification, XLNetModel
from biomarker_nlp.negation_cue_scope import CueModel, ScopeModel


__main__.gelu = F.gelu
__main__.relu = F.relu

for name, obj in inspect.getmembers(xlnet_mod):
    if inspect.isclass(obj):
        setattr(__main__, name, obj)

__main__.CueModel = CueModel
__main__.ScopeModel = ScopeModel
__main__.XLNetForTokenClassification = XLNetForTokenClassification
__main__.XLNetModel = XLNetModel

In [ ]:
modelCue = torch.load('/content/drive/MyDrive/Biomarker_Project/negCue', weights_only=False)

In [ ]:
modelScope = torch.load('/content/drive/MyDrive/Biomarker_Project/negScope', weights_only=False)

In [ ]:
df.head(5)

,therapy_label,disease_label,drug_label,raw_text,geneProtein_label
0,Idecabtagene Vicleucel,multiple myeloma,ABECMA- idecabtagene vicleucel suspension,NaN,*
1,Abemaciclib,Breast cancer,VERZENIO- abemaciclib tablet,\nVERZENIO® (abemaciclib) is indicated:\n\n\n\...,aromatase
2,Abiraterone Acetate,Prostate cancer,ZYTIGA- abiraterone acetate tablet,NaN,*
3,Paclitaxel Albumin-stabilized Nanoparticle For...,Pancreatic cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",NaN,*
4,Paclitaxel Albumin-stabilized Nanoparticle For...,Breast cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",\nABRAXANE is indicated for the treatment of b...,ABRAXANE

In [ ]:
modelCue

In [ ]:
import torch
import pandas as pd
from tqdm import tqdm
from biomarker_nlp import negation_cue_scope

tqdm.pandas(desc="Processing Stage 3")

def process_stage_3_final(row, nlp, modelCue, modelScope):
    text = str(row.get('raw_text', ''))
    disease = str(row.get('disease_label', '')).lower()

    if len(text) < 10:
        return "", "", "", ""

    doc = nlp(text)

    metastatic = ""
    first_line = ""
    accel_app = ""

    for token in doc:
        t_low = token.text.lower()

        if t_low in ["metastatic", "advanced", "recurrent", "stage iv"]:
            if token.dep_ in ["amod", "compound", "conj"]:
                metastatic = "Yes"
            elif any(d_word in [t.text.lower() for t in token.head.subtree] for d_word in disease.split()):
                metastatic = "Yes"

        if "first-line" in t_low or "untreated" in t_low:
            first_line = "Yes"

    if "accelerated approval" in text.lower():
        accel_app = "Yes"

    neg_scope_text = ""
    try:
        with torch.inference_mode():
            if negation_cue_scope.negation_detect(text, modelCue):
                scope_tokens = negation_cue_scope.negation_scope(text, modelCue, modelScope)
                neg_scope_text = " ".join(scope_tokens).lower()

                if metastatic == "Yes" and "metastatic" in neg_scope_text:
                    metastatic = ""
                if first_line == "Yes" and "first-line" in neg_scope_text:
                    first_line = ""
    except:
        pass

    return metastatic, first_line, accel_app, neg_scope_text

print("🚀 Initializing Stage 3: Deep Learning Analysis...")

results = df.progress_apply(
    lambda row: process_stage_3_final(row, nlp, modelCue, modelScope),
    axis=1
)

df[['metastatic', 'firstLine', 'acceleratedApproval', 'negGeProDr_label']] = pd.DataFrame(results.tolist(), index=df.index)

print("\nStage 3 Complete!")

🚀 Initializing Stage 3: Deep Learning Analysis...

Processing Stage 3:   0%|          | 0/1464 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Processing Stage 3: 100%|██████████| 1464/1464 [03:21<00:00,  7.26it/s]

Stage 3 Complete!

In [ ]:
df.to_csv("biomarkers.csv", index=False)

In [ ]:
df = df.dropna()

In [ ]:
df.drop(columns='raw_text',inplace = True)

/tmp/ipykernel_11966/1938333878.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns='raw_text',inplace = True)

In [ ]:
df.to_csv("biomarkers_without_Nan.csv",index = False)

In [ ]:
df

,therapy_label,disease_label,drug_label,geneProtein_label,metastatic,firstLine,acceleratedApproval,negGeProDr_label
1,Abemaciclib,Breast cancer,VERZENIO- abemaciclib tablet,aromatase,Yes,,,
4,Paclitaxel Albumin-stabilized Nanoparticle For...,Breast cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",ABRAXANE,Yes,,,
5,Paclitaxel Albumin-stabilized Nanoparticle For...,Non-small cell lung cancer,"ABRAXANE- paclitaxel injection, powder, lyophi...",ABRAXANE,Yes,Yes,,
6,Acalabrutinib Maleate Monohydrate,Chronic lymphocytic leukemia,"CALQUENCE- acalabrutinib capsule, gelatin coated",*,,,,
7,Acalabrutinib Maleate Monohydrate,Mantle cell lymphoma,"CALQUENCE- acalabrutinib capsule, gelatin coated",*,,Yes,,
...,...,...,...,...,...,...,...,...
1419,Zanubrutinib,Follicular lymphoma,BRUKINSA- zanubrutinib capsule,*,,,Yes,
1425,Vemurafenib,Erdheim-Chester disease,"ZELBORAF- vemurafenib tablet, film coated",BRAF,,,,
1426,Vemurafenib,Melanoma,"ZELBORAF- vemurafenib tablet, film coated",BRAF,Yes,,,
1429,Lurbinectedin,Small cell lung cancer,"ZEPZELCA- lurbinectedin injection, powder, lyo...",*,Yes,,Yes,
1462,Retifanlimab-dlwr,Merkel cell carcinoma,ZYNYZ- retifanlimab-dlwr injection,*,Yes,,,

In [ ]:
df.to_csv("biomarkers_without_Nan.csv",index = False)

#### Model Testing

In [5]:
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz

Collecting https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz
  Downloading https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bionlp13cg_md-0.5.4.tar.gz (119.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 8.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting spacy<3.8.0,>=3.7.4 (from en_ner_bionlp13cg_md==0.5.4)
  Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.0.13)
Collecting thinc<8.3.0,>=8.2.2 (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.0.10)
Collecting weasel<0.5.0,>=0.1.0 (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.24.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (4.67.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (26.1)
Collecting langcodes<4.0.0,>=3.2.0 (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading langcodes-3.5.1-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.0.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2026.4.22)
Collecting blis<0.8.0,>=0.7.8 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Collecting numpy>=1.19.0 (from spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.2 MB/s eta 0:00:00
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.0.4)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (7.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (2.1.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.4->en_ner_bionlp13cg_md==0.5.4) (0.1.2)
Downloading spacy-3.7.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 86.0 MB/s eta 0:00:00
Downloading langcodes-3.5.1-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.1/183.1 kB 18.1 MB/s eta 0:00:00
Downloading thinc-8.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (865 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.0/865.0 kB 55.2 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 24.7 MB/s eta 0:00:00
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 kB 5.8 MB/s eta 0:00:00
Downloading blis-0.7.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 109.5 MB/s eta 0:00:00
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Building wheels for collected packages: en_ner_bionlp13cg_md
  Building wheel for en_ner_bionlp13cg_md (setup.py) ... done
  Created wheel for en_ner_bionlp13cg_md: filename=en_ner_bionlp13cg_md-0.5.4-py3-none-any.whl size=119814670 sha256=fd7a66911adf59de3414c29bddf0448be629890215db2dc76b6a26be470ad5ae
  Stored in directory: /root/.cache/pip/wheels/95/ca/35/7a25decd9a4965ccae588698b6d96f92e1c6816d805f509590
Successfully built en_ner_bionlp13cg_md
Installing collected packages: numpy, langcodes, blis, confection, thinc, weasel, spacy, en_ner_bionlp13cg_md
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: blis
    Found existing installation: blis 1.3.3
    Uninstalling blis-1.3.3:
      Successfully uninstalled blis-1.3.3
  Attempting uninstall: confection
    Found existing installation: confection 1.3.3
    Uninstalling confection-1.3.3:
      Successfully uninstalled confection-1.3.3
  Attempting uninstall: thinc
    Found existing installation: thinc 8.3.13
    Uninstalling thinc-8.3.13:
      Successfully uninstalled thinc-8.3.13
  Attempting uninstall: weasel
    Found existing installation: weasel 1.0.0
    Uninstalling weasel-1.0.0:
      Successfully uninstalled weasel-1.0.0
  Attempting uninstall: spacy
    Found existing installation: spacy 3.8.14
    Uninstalling spacy-3.8.14:
      Successfully uninstalled spacy-3.8.14
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed blis-0.7.11 confection-0.1.5 en_ner_bionlp13cg_md-0.5.4 langcodes-3.5.1 numpy-1.26.4 spacy-3.7.5 thinc-8.2.5 weasel-0.4.3

In [2]:
import spacy

In [3]:
nlp = spacy.load("en_ner_bionlp13cg_md", disable=["tagger", "parser", "lemmatizer"])

/usr/local/lib/python3.12/dist-packages/spacy/language.py:2195: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

In [23]:
nlp.pipe_names

['tok2vec', 'attribute_ruler', 'ner']

In [20]:
doc = nlp("""
Treatment with Osimertinib is indicated for patients with metastatic non-small cell lung cancer (NSCLC)
who harbor the EGFR T790M mutation. While the drug effectively targets the EGFR protein, it is not recommended for patients without the T790M gene variant.
In contrast, Atezolizumab is utilized for advanced urothelial carcinoma regardless of PD-L1 expression,
though clinical data suggests it is not indicated as a first-line therapy for patients with untreated renal impairment.""")

In [24]:
from spacy import displacy
displacy.render(doc,style = 'ent')

In [21]:
doc.ents

(patients,
 metastatic non-small cell lung cancer,
 NSCLC,
 EGFR T790,
 EGFR,
 patients,
 T790M,
 urothelial carcinoma,
 PD-L1,
 patients,
 renal)

In [22]:
for ent in doc.ents:
  print(ent.text,'**',ent.label_)

patients ** ORGANISM
metastatic non-small cell lung cancer ** CANCER
NSCLC ** CANCER
EGFR T790 ** GENE_OR_GENE_PRODUCT
EGFR ** GENE_OR_GENE_PRODUCT
patients ** ORGANISM
T790M ** GENE_OR_GENE_PRODUCT
urothelial carcinoma ** CANCER
PD-L1 ** GENE_OR_GENE_PRODUCT
patients ** ORGANISM
renal ** CANCER